### ISSUE TITLE
Creation Date and Update Date are switched

### ISSUE THREAD

**Issue by 1337jay** [whois-team/whoisdigger#3]
The title says it all.

Btw any ETA on proxy integration?

Thanks for this awesome tool!

Alan

**Comment by eduardomota** [comment]
Hi, i suppose this was switched on bulk whois export, fixed on e5e01c8.

There is no ETA on proxy integration for now, i'm thinking about either making a separate dns proxy app to plugin into whoisdigger or implementing it directly into whoisdigger. 

Thank you for trying out the tool
