### ISSUE TITLE
Add support for .si domains

### ISSUE THREAD

**Issue by 1337jay** [whois-team/whoisdigger#4]
When doing whois for .si domains all fields are "null" or "Invalid Date". This is due to how the Slovenian registry handles out the data.. I will attach an example of a .si domain. Could you add support for .si domains so that the data gets handled correctly and is displayed in the .csv file?

Thanks

`%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This is ARNES whois database
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Rights restricted by copyright.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% The WHOIS service offered by Arnes, .si Registry, is
% provided for information purposes only. It allows persons
% to check whether a specific domain name is still available
% or not and to obtain information related to the registration
% records of existing domain names.
%
% This WHOIS service accepts and displays only ASCII characters.

% By submitting a query to our WHOIS lookup service, you agree
% to the restrictions on the use of WHOIS and WHOIS data as follows:
%      o You may not allow, enable or otherwise support
%        the transmission of unsolicited, commercial advertising
%        or other solicitations, whether via email or otherwise;
%      o You may not use the information to target advertising
%        in any possible way;
%      o You may not cause inconvenience the domain name holders
%        in any possible way by sending them messages
%        (whether by automated, electronic processes capable of
%        enabling high volumes or other possible means);
%      o You may not copy, extract and/or publish contents
%        of the WHOIS database.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

domain:		test.si
registrar:	Infonova REGISTRIRAJ.si DOMAINS.si
registrar-url:	http://www.registriraj.si
nameserver:	ns1.infonova.si
nameserver:	ns3.infonova.si
registrant:	G32766
status:		ok
created:	2005-04-04
expire:		2020-04-04
source:		ARNES

Domain holder:
NOT DISCLOSED

Tech:
NOT DISCLOSED

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Full domain details are available here http://www.registry.si
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
`

**Comment by eduardomota** [comment]
Added basic .si support with e5e01c8 commit on both single and bulk whois
