### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by 1337jay** [whois-team/whoisdigger#5]
Hey,

Basically I bulk scanned about 100k .com domains and ~20% of them were marked as available..but after manually checking (not all, but still a lot) of these domains they were still/already registered. Lots of domains also listed as “error” but that does not bother me much as I tried a few of them and they were all taken (so I assume they are all taken if an “error” is returned).

**Comment by eduardomota** [comment]
Hi,

the verification engine uses a list of patterns and checks if the reply contains any if not it will assume as available, i'm open to suggestions on improving the availability function, it would be helpful to know the tlds and some of the false positives so i could check their replies. If you're not comfortable posting them here you can send them to, community [at] whoisteam (dot) com.

**Comment by 1337jay** [comment]
Hi,

I just sent you an email with some examples.

Thanks.

**Comment by eduardomota** [comment]
1337jay writes:

> ...... There seems to be not enough checks in place for errors and whois responses in whoiswrapper.js
> 
> Adding a few lines fixed most if not all of the invalid statuses;
> 
>  case (resultsText.includes('error')): 
>  case (resultsText.includes('Error')):
>   return 'error';
> 
> And
> 
>  case (resultsText.includes('Expiration Date:')):
>  case (resultsText.includes('Expiry Date:')):
>   return 'unavailable';

 
Added adapted check on the latest commit 60cd6c646c8da2cbc51366d5e0f1ba86c9749287
Thank you for using the tool
